version: '2.6'

services:
  saga-coordinator:
    build:
      context: .
      dockerfile: Dockerfile
    image: saga
    ports:
      - '4000:4000'
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
