version: '2.6'

services:
  stock-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock
    ports:
      - '4003:4003'
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
