version: '2.6'

services:
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: customer
    ports:
      - '4002:4002'
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
